config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}

  root 'items#index'
  resources :items, :only => [:index, :new, :show, :create]
  resources :users, :only => [:index, :show, :edit]
  resources :pins

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :pins
	has_many :users , through: :pins

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	validates(:name, {
		:presence => true, 
	})
	validates(:description, :presence => true)
	validates(:price, :presence => true)
	validates(:avatar, :presence => true)
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :item
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :pins
	has_many :items, through: :pins

	validates(:name, :presence => true)
	validates(:user_name, :presence => true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end

	def create
		@item = Item.new(params["item"].permit(:name , :description, :price, :avatar))
		if @item.save
			redirect_to '/items'
		else
			render :new
		end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end
	def show
		@item = Item.find(params[:id])
	end
	def new
		@item = Item.new
	end

	def create
		@item = Item.new(params["item"].permit(:name , :description, :price, :avatar))
		if @item.save
			redirect_to '/items'
		else
			render :new
		end
	end
end

app/controllers/pin_controller.rb
class PinController < ApplicationController
	def create
		@pin = Pin.new
		@pin.user_id = current_user.id
		@pin.item_id = Item.find(params[:id]).id
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	def create
		@pin = Pin.new(:user_id => params[:user_id], :item_id => params[:item_id])
		@pin.save
		redirect_to '/items'
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	before_filter :configure_permitted_parameters

	protected

  	def configure_permitted_parameters
   	 devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :user_name,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :user_name, :current_password,
        :email, :password, :password_confirmation)
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
		@items = @user.items
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#	before action :authenticate_user!
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
		@items = @user.items
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/item/show.html.erb
<h1><%= @item.name %></h1>

<p>
<%= image_tag @item.avatar.url(:medium) %><br />
<%= @item.description %>
</p>

app/views/items/index.html.erb
<h1>Items</h1>


<ol>
<% @items.each do |item| %>
	<li>
	<%= image_tag item.avatar.url(:thumb) %>
	<%=link_to item.name, "items/#{item.id}" %>
	</li>
<% end %>
</ol>

<%=link_to "New Item", "items/new" %>

app/views/items/new.html.erb
<h1>New Item</h1>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this story from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @item do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.label :price %>:
  <%= f.number_field :price, :step => 'any' %><br />

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.submit %>
<% end %>

<%= link_to "Back" , "/items" %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<p>
<%= image_tag @item.avatar.url(:medium) %><br />
<%= @item.description %>
</p>

<% if user_signed_in? %>
<%= link_to "Like", pins_path(:user_id => current_user.id, :item_id => @item.id), :method => :post %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<header>
<%= link_to "Items" , "/items" %>
<%= link_to "Users" , "/users" %>
<% if user_signed_in? %>
  Signed in as 
  <%= link_to current_user.user_name, "/users/#{current_user.id}"%>
  |
  <%=link_to 'Sign Out', destroy_user_session_path, :method => :delete %> | <%=link_to 'Edit Profile', edit_user_registration_path %>
<% else %>
    <%= link_to 'Sign In', user_session_path %>
 <% end %>
</header>
<%= yield %>
</div>
</body>
</html>

app/views/user/index.html.erb
<h1>Users</h1>

<ol>
<% @users.each do |user| %>
	<li>
	<%= link_to user.user_name , "users/#{user.id}" %>
	</li>
<%end%>
</ol>

app/views/users/index.html.erb
<h1>Users</h1>

<ol>
<% @users.each do |user| %>
	<li>
	<%= link_to user.user_name , "users/#{user.id}" %>
	</li>
<%end%>
</ol>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<ol>
<% @items.each do |item| %>
	<li>
	<%=link_to item.name, "/items/#{item.id}" %>
	</li>
<% end %>
</ol>